# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CCNY Planetarium
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  The City College of New York has a planetarium.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ccnyplanetarium
facebook_username:  ccnyplanetarium
instagram_username: ccnyplanetarium
github_username: ccnyplanetarium
youtube_username: CCNY Planetarium
repository: ""

# Build settings
plugins:
  - jekyll-feed

# A list of the pages to display in the navigation bar
header_pages:
  - people.html
  - technical.html

collections:
  terrain:
    output: true
    permalink: terrain/:title
    layout: terrain-detail

defaults:
  - scope:
      path: ""
      type: terrain
    values:
      layout: terrain-detail

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, _site, src, vendor, CNAME, LICENSE, Rakefile, old, constellation-guide]
